version: '3.8'
services:
  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5433:5432

    environment:
      POSTGRES_DB: prismadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  dbdata: